import { ListItem } from 'carbon-components-angular';
import {
  CORRELATIVE_CURSADA_NAME,
  FIRST_QUARTER_NAME,
  INGENIERIA_DE_SISTEMAS_NAME,
  ISubject,
  SECOND_QUARTER_NAME,
  TUDAI_NAME,
} from './interfaces';

export const CAREERS_DROPDOWN_ITEMS: ListItem[] = [
  {
    content: 'Todas',
    value: 'Todas',
    selected: true,
  },
  {
    content: INGENIERIA_DE_SISTEMAS_NAME,
    value: INGENIERIA_DE_SISTEMAS_NAME,
    selected: false,
  },
  { content: TUDAI_NAME, value: TUDAI_NAME, selected: false },
];

export const QUARTERS_DROPDOWN_ITEMS: ListItem[] = [
  {
    content: 'Todos',
    value: 'Todos',
    selected: true,
  },
  {
    content: FIRST_QUARTER_NAME,
    value: FIRST_QUARTER_NAME,
    selected: false,
  },
  { content: SECOND_QUARTER_NAME, value: SECOND_QUARTER_NAME, selected: false },
];

export let algebra_1: ISubject = {
  id: 'algebra_1',
  name: 'Álgebra I',
  status: localStorage.getItem('algebra_1'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Velazquez, Maria Ester',
  contactEmail: 'mary.velazquez2011@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0003',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0003',
  webLink: '',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=604',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let algebra_1_recursada: ISubject = {
  id: 'algebra_1_recursada',
  name: 'Álgebra I (Recursada)',
  status: localStorage.getItem('algebra_1_recursada'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: SECOND_QUARTER_NAME,
  teacher: 'Morelli, Graciela',
  contactEmail: 'morelligracielaangelica@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0003',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0003',
  webLink: '',
  moodleLink: '',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let algebra_lineal: ISubject = {
  id: 'algebra_lineal',
  name: 'Álgebra Lineal',
  status: localStorage.getItem('algebra_lineal'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: SECOND_QUARTER_NAME,
  teacher: 'Calomino, Ismael',
  contactEmail: 'ismaelcalomino@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0125',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0125',
  webLink: 'http://algebra-lineal.alumnos.exa.unicen.edu.ar/',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=761',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [
    { typeOfCorrelativity: CORRELATIVE_CURSADA_NAME, subject: algebra_1 },
  ],
};

export let algebra_lineal_recursada: ISubject = {
  id: 'algebra_lineal_recursada',
  name: 'Álgebra Lineal (Recursada)',
  status: localStorage.getItem('algebra_lineal_recursada'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Nagy, Agustin',
  contactEmail: 'agustin.nagy@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0125',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0125',
  webLink: '',
  moodleLink: '',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_matematico_1: ISubject = {
  id: 'analisis_matematico_1',
  name: 'Análisis Matemático I',
  status: localStorage.getItem('analisis_matematico_1'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Madrid, Ana Paula',
  contactEmail: 'apmadrid@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0500',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0500',
  webLink: 'https://analisis-matematico-i.alumnos.exa.unicen.edu.ar/',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=712',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_matematico_1_recursada: ISubject = {
  id: 'analisis_matematico_1_recursada',
  name: 'Análisis Matemático I (Recursada)',
  status: localStorage.getItem('analisis_matematico_1_recursada'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: SECOND_QUARTER_NAME,
  teacher: 'Maestri, Maria Laura',
  contactEmail: 'marialauramaestri@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0500',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0500',
  webLink: 'https://analisis-matematico-i.alumnos.exa.unicen.edu.ar/',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/view.php?id=712',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_matematico_2: ISubject = {
  id: 'analisis_matematico_2',
  name: 'Análisis Matemático II',
  status: localStorage.getItem('analisis_matematico_2'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Galotto, Maria Jose',
  contactEmail: 'mariajogalotto@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0504',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0504',
  webLink: 'http://analisis-matematico-ii.alumnos.exa.unicen.edu.ar/',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=664',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_matematico_2_recursada: ISubject = {
  id: 'analisis_matematico_2_recursada',
  name: 'Análisis Matemático II (Recursada)',
  status: localStorage.getItem('analisis_matematico_2_recursada'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: SECOND_QUARTER_NAME,
  teacher: '',
  contactEmail: '',
  modalidadLink: '',
  programaLink: '',
  webLink: '',
  moodleLink: '',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_y_diseño_de_algoritmos_1: ISubject = {
  id: 'analisis_y_diseño_de_algoritmos_1',
  name: 'Análisis y Diseño de Algoritmos I',
  status: localStorage.getItem('analisis_y_diseño_de_algoritmos_1'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Favre, Liliana Maria',
  contactEmail: 'liliana.favre@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0009',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0009',
  webLink: '',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=740',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_y_diseño_de_algoritmos_2: ISubject = {
  id: 'analisis_y_diseño_de_algoritmos_2',
  name: 'Análisis y Diseño de Algoritmos II',
  status: localStorage.getItem('analisis_y_diseño_de_algoritmos_2'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: SECOND_QUARTER_NAME,
  teacher: 'Favre, Liliana Maria',
  contactEmail: 'liliana.favre@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0013',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0013',
  webLink: '',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=766',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let analisis_y_diseño_de_algoritmos_2_recursada: ISubject = {
  id: 'analisis_y_diseño_de_algoritmos_2_recursada',
  name: 'Análisis y Diseño de Algoritmos II (Recursada)',
  status: localStorage.getItem('analisis_y_diseño_de_algoritmos_2_recursada'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Cifuentes, Maria Virginia',
  contactEmail: 'mvcifuentes@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0013',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0013',
  webLink: '',
  moodleLink: '',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let arquitectura_de_computadoras_1: ISubject = {
  id: 'arquitectura_de_computadoras_1',
  name: 'Arquitectura de Computadoras I',
  status: localStorage.getItem('arquitectura_de_computadoras_1'),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Tosini, Marcelo',
  contactEmail: 'marcelo.tosini@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0021',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0021',
  webLink: '',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=610',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let arquitectura_de_computadoras_y_tecnicas_digitales: ISubject = {
  id: 'arquitectura_de_computadoras_y_tecnicas_digitales',
  name: 'Arquitectura de Computadoras y Técnicas Digitales',
  status: localStorage.getItem(
    'arquitectura_de_computadoras_y_tecnicas_digitales'
  ),
  career: INGENIERIA_DE_SISTEMAS_NAME,
  quarter: FIRST_QUARTER_NAME,
  teacher: 'Tosini, Marcelo',
  contactEmail: 'marcelo.tosini@gmail.com',
  modalidadLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0027',
  programaLink:
    'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0027',
  webLink: '',
  moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=611',
  clasesLink: '',
  resumenesLink: '',
  parcialesLink: '',
  finalesLink: '',
  correlatives: [],
};

export let SUBJECTS: ISubject[] = [
  algebra_1,
  algebra_1_recursada,
  algebra_lineal,
  algebra_lineal_recursada,
  analisis_matematico_1,
  analisis_matematico_1_recursada,
  analisis_matematico_2,
  analisis_matematico_2_recursada,
  analisis_y_diseño_de_algoritmos_1,
  analisis_y_diseño_de_algoritmos_2,
  analisis_y_diseño_de_algoritmos_2_recursada,
  arquitectura_de_computadoras_1,
  arquitectura_de_computadoras_y_tecnicas_digitales,
  {
    id: '',
    name: 'Bases de Datos I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Del Fresno, Mirta Mariana',
    contactEmail: 'mdelfres@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0023',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0023',
    webLink: 'https://bdatos1.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=721',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Ciencias de la Computación I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0004',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0004',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=739',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Ciencias de la Computación I (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0004',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0004',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Ciencias de la Computación II',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0008',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0008',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=644',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Ciencias de la Computación II (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Schiaffino, Silvia Noemi',
    contactEmail: 'silvia.schiaffino@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0008',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0008',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Comunicación de Datos I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Mayorano, Fernando',
    contactEmail: 'fermayorano@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0014',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0014',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=771',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Comunicación de Datos II',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Rubiales, Aldo Jose',
    contactEmail: 'aldorubiales@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0029',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0029',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=669',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Diseño de Compiladores I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Ridao, Marcela Natividad',
    contactEmail: 'marceridao@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0032',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0032',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=778',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Diseño de Sistemas de Software',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Electricidad y Magnetismo',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Irurzun, Alicia',
    contactEmail: 'imalicia@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0012',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0012',
    webLink:
      'https://drive.google.com/drive/folders/1IpRsJmRVRwEgmuy9b4ktLdegFyrv2KCd',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=657',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Electrónica Digital',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Wainschenker, Ruben',
    contactEmail: 'ruben.wain@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0016',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0016',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=747',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Estructuras de Almacenamiento de Datos',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Rinaldi, Pablo Rafael',
    contactEmail: 'rinaldipablo@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0019',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0019',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=637',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Fundamentos de Economía y Proyectos de Inversión',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Física General',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Tognana, Sebastian',
    contactEmail: 'stognana@exa.unicen.edu.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0007',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0007',
    webLink: 'https://fisica-general.alumnos.exa.unicen.edu.ar/home',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=749',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Física General (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Morando, Carina',
    contactEmail: 'carinamorando@yahoo.com.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0007',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0007',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Ingeniería de Software',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Inglés',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Batrandiaran, Carolina',
    contactEmail: '',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0017',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0017',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=710',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción a la Arquitectura de Sistemas',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Curti, Hugo Javier',
    contactEmail: 'hcurti@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=1024',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=1024',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=593',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción a la Programación I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Cobo, Hernan',
    contactEmail: 'hernanjcobo@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0001',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0001',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=737',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción a la Programación I (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Leonardi, Carmen',
    contactEmail: '',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0001',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0001',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción a la Programación II',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Cobo, Hernan',
    contactEmail: 'hcobo@rec.unicen.edu.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0005',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0005',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=780',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción a la Programación II (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Boroni, Gustavo Adolfo',
    contactEmail: 'gboroni@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0005',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0005',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Introducción al Cálculo Diferencial e Integral',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Marinelli, Claudia Beatriz',
    contactEmail: 'marinelli.claudia@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0030',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0030',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=615',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Investigación Operativa I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Illescas, Roberto Gustavo',
    contactEmail: 'gustavo.illescas@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0026',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0026',
    webLink: 'http://invop.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=717',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Legislación y Gestión Ambiental',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Mauhourat, Ricardo',
    contactEmail: 'ricardo.mauhourat@mauhourat.com.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=1190',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=1190',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=626',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Lenguajes de Programación I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Massa, Jose Maria',
    contactEmail: 'josem.massa@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0024',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0024',
    webLink: 'https://lengprg1.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=562',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Matemática Discreta',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Velazquez, Maria Ester',
    contactEmail: 'mary.velazquez2011@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0127',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0127',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=718',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Matemática Discreta (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Bigeon, Juan Jose',
    contactEmail: 'jbigeon@exa.unicen.edu.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0127',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0127',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Metodologías de Desarrollo de Software I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Marcos, Claudia Andrea',
    contactEmail: 'cmarcos@exa.unicen.edu.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0020',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0020',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=599',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Organización Empresarial',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Illescas, Roberto Gustavo',
    contactEmail: 'gustavo.illescas@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=1188',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=1188',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=616',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Probabilidades y Estadística',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Marinelli, Claudia Beatriz',
    contactEmail: 'marinelli.claudia@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0015',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0015',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=704',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Programación Exploratoria',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Programación Orientada a Objetos',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Berdun, Luis Sebastian',
    contactEmail: 'lberdun@exa.unicen.edu.ar',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0022',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0022',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Programación Orientada a Objetos (Recursada)',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Teyseyre, Alfredo',
    contactEmail: 'alfredo.teyseyre@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0022',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0022',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Química',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Sistemas Operativos I',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Zunino, Alejandro Octavio',
    contactEmail: 'azunino@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0025',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0025',
    webLink: 'https://users.exa.unicen.edu.ar/catedras/sisop1/',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: 'Teoría de la Información',
    status: localStorage.getItem(''),
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Del Fresno, Mirta Mariana',
    contactEmail: 'mdelfres@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0028',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0028',
    webLink: 'https://teoinfo.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=643',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
  {
    id: '',
    name: '',
    status: localStorage.getItem(''),
    career: TUDAI_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
    correlatives: [],
  },
];
