import { ListItem } from 'carbon-components-angular';
import {
  FIRST_QUARTER_NAME,
  INGENIERIA_DE_SISTEMAS_NAME,
  ISubjectType,
  SECOND_QUARTER_NAME,
  TUDAI_NAME,
} from './interfaces';

export const CAREERS_DROPDOWN_ITEMS: ListItem[] = [
  {
    content: 'Todas',
    value: 'Todas',
    selected: true,
  },
  {
    content: INGENIERIA_DE_SISTEMAS_NAME,
    value: INGENIERIA_DE_SISTEMAS_NAME,
    selected: false,
  },
  { content: TUDAI_NAME, value: TUDAI_NAME, selected: false },
];

export const QUARTERS_DROPDOWN_ITEMS: ListItem[] = [
  {
    content: 'Todos',
    value: 'Todos',
    selected: true,
  },
  {
    content: FIRST_QUARTER_NAME,
    value: FIRST_QUARTER_NAME,
    selected: false,
  },
  { content: SECOND_QUARTER_NAME, value: SECOND_QUARTER_NAME, selected: false },
];

export const SUBJECTS: ISubjectType[] = [
  {
    name: 'Álgebra I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Velazquez, Maria Ester',
    contactEmail: 'mary.velazquez2011@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0003',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0003',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=604',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Álgebra I (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Morelli, Graciela',
    contactEmail: 'morelligracielaangelica@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0003',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0003',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Álgebra Lineal',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Calomino, Ismael',
    contactEmail: 'ismaelcalomino@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0125',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0125',
    webLink: 'http://algebra-lineal.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=761',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Álgebra Lineal (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Nagy, Agustin',
    contactEmail: 'agustin.nagy@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0125',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0125',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis Matemático I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Madrid, Ana Paula',
    contactEmail: 'apmadrid@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0500',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0500',
    webLink: 'https://analisis-matematico-i.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=712',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis Matemático I (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Maestri, Maria Laura',
    contactEmail: 'marialauramaestri@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0500',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0500',
    webLink: 'https://analisis-matematico-i.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/view.php?id=712',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis Matemático II',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Galotto, Maria Jose',
    contactEmail: 'mariajogalotto@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0504',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0504',
    webLink: 'http://analisis-matematico-ii.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=664',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis Matemático II (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis y Diseño de Algoritmos I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Favre, Liliana Maria',
    contactEmail: 'liliana.favre@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0009',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0009',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=740',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis y Diseño de Algoritmos II',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Favre, Liliana Maria',
    contactEmail: 'liliana.favre@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0013',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0013',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=766',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Análisis y Diseño de Algoritmos II (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Cifuentes, Maria Virginia',
    contactEmail: 'mvcifuentes@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0013',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0013',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Arquitectura de Computadoras I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Tosini, Marcelo',
    contactEmail: 'marcelo.tosini@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0021',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0021',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=610',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Arquitectura de Computadoras y Técnicas Digitales',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Tosini, Marcelo',
    contactEmail: 'marcelo.tosini@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0027',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0027',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=611',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Bases de Datos I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Del Fresno, Mirta Mariana',
    contactEmail: 'mdelfres@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0023',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0023',
    webLink: 'https://bdatos1.alumnos.exa.unicen.edu.ar/',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=721',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Ciencias de la Computación I',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: SECOND_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0004',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0004',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=739',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Ciencias de la Computación I (Recursada)',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0004',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0004',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: 'Ciencias de la Computación II',
    career: INGENIERIA_DE_SISTEMAS_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: 'Mauco, Maria Virginia',
    contactEmail: 'virginiamauco@gmail.com',
    modalidadLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=planificacion&materia=0008',
    programaLink:
      'https://aplicaciones.exa.unicen.edu.ar/Docentes/1.0/ws.php?servicio=programa&materia=0008',
    webLink: '',
    moodleLink: 'https://moodle.exa.unicen.edu.ar/course/edit.php?id=644',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
  {
    name: '',
    career: TUDAI_NAME,
    quarter: FIRST_QUARTER_NAME,
    teacher: '',
    contactEmail: '',
    modalidadLink: '',
    programaLink: '',
    webLink: '',
    moodleLink: '',
    clasesLink: '',
    resumenesLink: '',
    parcialesLink: '',
    finalesLink: '',
  },
];
